### ISSUE TITLE
Create Inbox? WTF? Send request failed.

### ISSUE THREAD

**Issue by luciash** [vexl-it/vexl#148]
Hi,
wanted to send my first request but by pressing the "Send request" button I got this very confusing message:
![IMG_4508](https://user-images.githubusercontent.com/4555037/203344767-4db418c7-645c-4361-aac4-91b3f449eed5.jpg)

Inbox? WTF? What is that and how should I create it?

Vexl App Version 1.0.16
iOS 15.7.1

**Comment by prusnak** [comment]
The person whe created the offer has already deleted it, but you phone didn't get the notification it should remove it from the marketplace.

I think we were already fixing this? Do you remember if that is the case @leomira ?

**Comment by leomira** [comment]
This should be fixed with deployment of #41 in the next release

**Comment by luciash** [comment]
Hi, tested in 1.0.17 and the issue remains. The expired offer is still there and the same error appears. Any ideas?
![image](https://user-images.githubusercontent.com/4555037/207670029-111a12ce-9116-4af9-89db-c410b3da31e5.png)

**Comment by prusnak** [comment]
> Hi, tested in 1.0.17 and the issue remains.

Can you try again with 1.0.18 installed?

**Comment by leomira** [comment]
@prusnak @luciash I just want to note here that 1.0.18 is not publicly available yet, should be so on Monday, 19.12.

**Comment by prusnak** [comment]
> should be so on Monday, 19.12.

Ah, sorry, I was confused. So yeah, please re-test on Monday with 1.0.18 if possible @luciash, thanks!

**Comment by luciash** [comment]
> > should be so on Monday, 19.12.
> 
> Ah, sorry, I was confused. So yeah, please re-test on Monday with 1.0.18 if possible @luciash, thanks!

Sure, I will re-test on Monday!

**Comment by leomira** [comment]
@luciash the new version was finally made available public in app store, please try downloading it and let us know if the problem persists 🙏

**Comment by luciash** [comment]
> @luciash the new version 1.0.21 was finally made available public in app stores, please try downloading it and let us know if the problem persists 🙏

This is some hella stubborn bug! Sorry, but I updated, tested in 1.0.21 and it still persist! Any chance I could have a peak at the part of the code which should supposedly fix this? Very weird that it changed basically nothing...

**Comment by leomira** [comment]
@prusnak can this be happening because the counterparty does not have the app updated, so their app does not handle new offer TTL (#41 )?

**Comment by prusnak** [comment]
> can this be happening because the counterparty does not have the app updated, so their app does not handle new offer TTL (#41)?

I guess we still need to wait until the broken offer expires? Is that 30 days by default?

**Comment by luciash** [comment]
> > can this be happening because the counterparty does not have the app updated, so their app does not handle new offer TTL (#41)?
> 
> I guess we still need to wait until the broken offer expires? Is that 30 days by default?

Sounds good but remember I reported this Nov 22, and today it's Dec 26th and it's still there.

**Comment by prusnak** [comment]
> Sounds good but remember I reported this Nov 22, and today it's Dec 26th and it's still there.

Right, but the backend change which does the purge after 30 days of inactivity was not deployed on Nov 22, but at some later date (somewhere around 1.0.18 release).

**Comment by luciash** [comment]
Sorry, but nothing has changed. The invalid buying offer is still hanging in there :( Version 10.0.24

**Comment by peterlaurinec** [comment]
And still present in iOS app version 1.0.27

**Comment by leomira** [comment]
handled in Vexl 2.0
