### ISSUE TITLE
Offers from friends are shown as "friend of a friend offer" with no common friends

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#50]
It should read "Friend offer" instead of "Friend of a friend"

**Comment by prusnak** [comment]
> are you @prusnak _sure_ that the offer what you're seeing is from your direct friend?

For the 2 cases I encountered this problem they were indeed my direct friends. But yeah, they are more ways how to trigger this.

**Comment by zaplmi** [comment]
Also, one of my direct contacts sees my offer (and vice versa) as posted by "friend of a friend" however common friends **are** listed.
Issue persists even after the recent backend update. 

1.0.7-295 - iOS-15.6.1

**Comment by mpocuch** [comment]
should be fixed with #60 can you pls confirm on the reported cases?

**Comment by slush0** [comment]
No, it is probably not fixed yet. The problem (also) lies in wrong handling of friend_level flag, which is (hopefully) going to be fixed in #96

**Comment by leomira** [comment]
fixed now
