### ISSUE TITLE
Checklist: Change order of messages

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#780]
Let's change order of the messages for every chat scenario - VexlBot shall appear as the last one. 

![Image](https://github.com/vexl-it/vexl/assets/25779015/f358ddd4-0fe4-4604-af4c-4a5d44a42445)
![Image](https://github.com/vexl-it/vexl/assets/25779015/44ca9d1f-b1f5-4c36-8c1c-8917cd57e746)

**Comment by kaladivo** [comment]
Fixed: 



![Image](https://github.com/vexl-it/vexl/assets/11568934/fac12aa3-62ee-4e52-ba3b-4799aa5ae0e1)

**Comment by leomira** [comment]
This is not fixed (latest staging):


![Image](https://github.com/vexl-it/vexl/assets/25779015/a4803b8f-6b0d-4641-ab29-ec87db6c7211)
![Image](https://github.com/vexl-it/vexl/assets/25779015/8d3e4e93-8203-4d54-b470-dcbdbcdf2ed2)

**Comment by leomira** [comment]
But after I fill up the first part of the checklist, the order updates correctly: 


![Image](https://github.com/vexl-it/vexl/assets/25779015/373cbb38-ec96-4f5f-b7a0-bc93f4e2b1b2)



![Image](https://github.com/vexl-it/vexl/assets/25779015/a45c311a-64e6-43e8-9219-252f5ccd4298)
